### ISSUE TITLE
Various comments

### ISSUE THREAD

**Issue by tomaarsen** [MinishLab/model2vec#38]
Hello (again)!

After experimenting with the project some more, I've found a few points of potential improvements. I'll aggregate them here if that's okay:

- [ ] Set `device=None` as the default in `distill`, rather than `"cpu"`. This should use Sentence Transformers' functionality to get the "strongest" available device by default (e.g. "cuda" first). P.s.: distilling `mxbai-embed-large-v1` takes 00:05 seconds on my GPU vs 01:58 on CPU. (Edit: Might be moot since #35)
- [ ] Allow 1) passing an initialized Sentence Transformer model or 2) introduce the `trust_remote_code` argument. This is required for loading models with custom code, such as https://huggingface.co/jinaai/jina-embeddings-v2-base-en or https://huggingface.co/nomic-ai/nomic-embed-text-v1.5. (Edit: Might be moot since #35)
- [x] Don't be afraid to link to yourself in the README.md, i.e. in the bottom of the model card template you could put a hyperlink over your names to your GitHub or something. I've included this in #37.
- [ ] In my experience, the `private` argument in `push_to_hub` is quite well liked, it allows people to look the model (card) over before making the model public to everyone.
- [ ] The `token` argument in `push_to_hub` should be optional. If it's not specified, then the Hugging Face tools will automatically load it from your local filesystem if you ever did `huggingface-cli login`.
- [ ] "Model Authors" in the model card is a bit of a misnomer: if someone else trained the model then they're the authors, you're the Model2Vec authors.
- [ ] You can add "Model2Vec models on Hugging Face" or something to the Additional Resources, linking to https://huggingface.co/models?library=model2vec, if you want.

---

- Tom Aarsen

**Comment by stephantul** [comment]
Let me reply to these in order:

1. As you mention, we're removing sentence transformers as a dependency because we'd like to avoid circular dependency issues.
2. Idem
3. Thanks for the PR, much appreciated.
4. Good point, adding it in PR
5. Ok, makes sense
6. Also makes sense
7. Cool, will also add.

I'll update this with references to the PRs.

**Comment by stephantul** [comment]
Fixed in #39 and #36 thanks!

**Comment by tomaarsen** [comment]
Awesome! Nice work
